In [1]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 59.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 236.8/236.8 kB 28.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 73.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 75.5 MB/s eta 0:00:00


In [4]:
from transformers import AutoTokenizer

In [6]:
checkpoint='bert-base-uncased'
tokenizer=AutoTokenizer.from_pretrained(checkpoint)

In [7]:
tokenizer('hello world')

{'input_ids': [101, 7592, 2088, 102], 'token_type_ids': [0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1]}

In [9]:
tokens=tokenizer.tokenize('hello world')
tokens

['hello', 'world']

In [11]:
ids=tokenizer.convert_tokens_to_ids(tokens)
ids


[7592, 2088]

In [12]:
tokenizer.convert_ids_to_tokens(ids)

['hello', 'world']

In [13]:
tokenizer.decode(ids)

'hello world'

In [14]:
ids=tokenizer.encode('hello world')
ids

[101, 7592, 2088, 102]

In [15]:
tokenizer.convert_ids_to_tokens(ids)

['[CLS]', 'hello', 'world', '[SEP]']

In [16]:
tokenizer.decode(ids)

'[CLS] hello world [SEP]'

In [17]:
model_inputs=tokenizer('hello world')
model_inputs

{'input_ids': [101, 7592, 2088, 102], 'token_type_ids': [0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1]}

In [18]:
data=[
    'I like cats',
    'Do you like cats too?'

]

In [19]:
from transformers import AutoModelForSequenceClassification

In [20]:
model=AutoModelForSequenceClassification.from_pretrained(checkpoint)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly i

In [21]:
outputs=model(**model_inputs)

AttributeError: ignored

In [24]:
model_inputs=tokenizer('hello world',return_tensors='pt')
outputs=model(**model_inputs)
outputs


SequenceClassifierOutput(loss=None, logits=tensor([[-0.2182, -0.2389]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [25]:
model=AutoModelForSequenceClassification.from_pretrained(
    checkpoint,num_labels=3
)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly i

In [26]:

outputs=model(**model_inputs)
outputs

SequenceClassifierOutput(loss=None, logits=tensor([[ 0.2379, -0.0405, -0.0854]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [28]:
outputs.logits

tensor([[ 0.2379, -0.0405, -0.0854]], grad_fn=<AddmmBackward0>)

In [29]:
outputs['logits']

tensor([[ 0.2379, -0.0405, -0.0854]], grad_fn=<AddmmBackward0>)

In [33]:
outputs[0]

tensor([[ 0.2379, -0.0405, -0.0854]], grad_fn=<AddmmBackward0>)

In [34]:
outputs.logits.detach().cpu().numpy()

array([[ 0.23789532, -0.04052146, -0.08544768]], dtype=float32)

In [35]:
data=[
    'I like cats',
    'Do you like cats too?'

]
model_inputs=tokenizer('hello world',return_tensors='pt')
outputs=model(**model_inputs)
outputs


SequenceClassifierOutput(loss=None, logits=tensor([[ 0.2379, -0.0405, -0.0854]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [37]:
model_inputs=tokenizer(data,padding=True,truncation=True,return_tensors='pt')
model_inputs

{'input_ids': tensor([[ 101, 1045, 2066, 8870,  102,    0,    0,    0],
        [ 101, 2079, 2017, 2066, 8870, 2205, 1029,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1]])}

In [38]:
model_inputs['input_ids']

tensor([[ 101, 1045, 2066, 8870,  102,    0,    0,    0],
        [ 101, 2079, 2017, 2066, 8870, 2205, 1029,  102]])

In [39]:
model_inputs['attention_mask']

tensor([[1, 1, 1, 1, 1, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1]])

In [41]:
outputs=model(**model_inputs)
outputs

SequenceClassifierOutput(loss=None, logits=tensor([[ 0.0673, -0.0439,  0.0758],
        [ 0.4295, -0.1435,  0.0366]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)